"""Every source behind drip's numbers. Full discussion: RESEARCH.md.

kind: peer-reviewed | government | industry | analysis | pricing | reference
"""

SOURCES = [
    {"id": "li", "kind": "peer-reviewed", "year": 2025,
     "title": "Making AI Less “Thirsty”: Uncovering and Addressing the Secret Water Footprint of AI Models",
     "authors": "Li, Yang, Islam, Ren — Communications of the ACM 68(7)",
     "url": "https://doi.org/10.1145/3724499", "alt": ("arXiv", "https://arxiv.org/abs/2304.03271"),
     "finding": "Framework for on-site (cooling) + off-site (electricity) water; US average 16.9 mL per GPT-3 request; US EWIF 3.14 L/kWh (WRI).",
     "used_for": "water framework, off-site water factor (MID)"},
    {"id": "lbnl", "kind": "government", "year": 2024,
     "title": "2024 United States Data Center Energy Usage Report",
     "authors": "Shehabi et al. — Lawrence Berkeley National Laboratory (US DOE)",
     "url": "https://eta-publications.lbl.gov/sites/default/files/2024-12/lbnl-2024-united-states-data-center-energy-usage-report_1.pdf",
     "finding": "Indirect water 4.52 L/kWh (data-center-weighted), US grid 4.35 L/kWh; average on-site WUE ≈ 0.36 L/kWh.",
     "used_for": "off-site water factor (HIGH), on-site WUE (MID)"},
    {"id": "google", "kind": "industry", "year": 2025,
     "title": "Measuring the environmental impact of delivering AI at Google scale",
     "authors": "Elsworth, Huang, Patterson et al. — Google",
     "url": "https://arxiv.org/abs/2508.15734",
     "finding": "Median Gemini text prompt: 0.24 Wh, 0.26 mL water (on-site only, WUE 1.15 L/kWh); 1.72× full-stack energy factor.",
     "used_for": "on-site WUE (HIGH), full-stack energy factor, sanity check"},
    {"id": "mlenergy", "kind": "peer-reviewed", "year": 2025,
     "title": "The ML.ENERGY Benchmark: Toward Automated Inference Energy Measurement and Optimization",
     "authors": "Chung et al. — NeurIPS 2025 Datasets & Benchmarks",
     "url": "https://arxiv.org/abs/2505.06371", "alt": ("leaderboard data", "https://github.com/ml-energy/leaderboard"),
     "finding": "Measured 0.6–2.4 J per output token for frontier-scale open models at production batch sizes (H100/B200).",
     "used_for": "energy per output token (LOW–MID)"},
    {"id": "oviedo", "kind": "peer-reviewed", "year": 2026,
     "title": "Energy use of AI inference, efficiency pathways, and test-time scaling",
     "authors": "Oviedo et al. — Microsoft, Joule",
     "url": "https://www.cell.com/joule/fulltext/S2542-4351(26)00114-5", "alt": ("arXiv", "https://arxiv.org/abs/2509.20241"),
     "finding": "Frontier models on H100: median 0.31 Wh per query (~300 output tokens); long reasoning 3.91 Wh.",
     "used_for": "energy per output token (MID)"},
    {"id": "jegham", "kind": "analysis", "year": 2025,
     "title": "How Hungry is AI? Benchmarking Energy, Water, and Carbon Footprint of LLM Inference",
     "authors": "Jegham et al. — preprint",
     "url": "https://arxiv.org/abs/2505.09598",
     "finding": "Claude 3.7 Sonnet ≈ 0.95–5.7 Wh per query depending on prompt size (modelled at small batch sizes).",
     "used_for": "energy per output token (HIGH)"},
    {"id": "epoch", "kind": "analysis", "year": 2025,
     "title": "How much energy does ChatGPT use?",
     "authors": "Josh You — Epoch AI",
     "url": "https://epoch.ai/gradient-updates/how-much-energy-does-chatgpt-use",
     "finding": "≈0.3 Wh per typical GPT-4o query; energy grows with input length (≈2.5 Wh at 10K tokens).",
     "used_for": "energy per input token"},
    {"id": "couch", "kind": "analysis", "year": 2026,
     "title": "Electricity use of AI coding agents",
     "authors": "Simon P. Couch (blog)",
     "url": "https://simonpcouch.com/blog/2026-01-20-cc-impact/",
     "finding": "Claude Code estimate: input 390, output 1,950, cache read 39, cache write 490 Wh per million tokens.",
     "used_for": "input / cache energy (MID–HIGH)"},
    {"id": "hausfather", "kind": "analysis", "year": 2026,
     "title": "The real energy use of agentic AI",
     "authors": "Zeke Hausfather — The Climate Brink",
     "url": "https://www.theclimatebrink.com/p/the-real-energy-use-of-agentic-ai",
     "finding": "8 weeks of Claude Code (3.2B tokens, ~96% cache reads) ≈ 170 kWh (70–330); cache-read cost bounded at 1–25% of input.",
     "used_for": "cache-read range (LOW/HIGH), sanity check"},
    {"id": "luccioni", "kind": "peer-reviewed", "year": 2024,
     "title": "Power Hungry Processing: Watts Driving the Cost of AI Deployment?",
     "authors": "Luccioni, Jernite, Strubell — ACM FAccT ’24",
     "url": "https://arxiv.org/abs/2311.16863",
     "finding": "Text generation ≈ 0.047 kWh per 1,000 inferences for models up to ~11B parameters.",
     "used_for": "background / scaling with model size"},
    {"id": "aws", "kind": "industry", "year": 2025,
     "title": "AWS Cloud — Amazon Sustainability",
     "authors": "Amazon",
     "url": "https://sustainability.aboutamazon.com/products-services/aws-cloud",
     "finding": "WUE 0.12 L/kWh (withdrawal), PUE 1.14–1.15.",
     "used_for": "on-site WUE (LOW), PUE"},
    {"id": "microsoft", "kind": "industry", "year": 2025,
     "title": "Measuring energy and water efficiency for Microsoft datacenters",
     "authors": "Microsoft",
     "url": "https://datacenters.microsoft.com/sustainability/efficiency/",
     "finding": "Global WUE 0.27 L/kWh, PUE 1.17 (FY25).",
     "used_for": "on-site WUE range"},
    {"id": "wri", "kind": "reference", "year": 2020,
     "title": "Guidance for Calculating Water Use Embedded in Purchased Electricity",
     "authors": "Reig, Luo, Christensen, Sinistore — World Resources Institute (cited via Li et al.)",
     "url": "https://www.wri.org/research/guidance-calculating-water-use-embedded-purchased-electricity",
     "finding": "Water consumed per kWh of electricity by generation source and region.",
     "used_for": "off-site water factor (LOW/MID)"},
    {"id": "anthropic-pricing", "kind": "pricing", "year": 2026,
     "title": "Claude API pricing",
     "authors": "Anthropic",
     "url": "https://platform.claude.com/docs/en/about-claude/pricing",
     "finding": "Per-model input/output/cache prices; cache read 0.025–0.1× input, cache write 1.25×.",
     "used_for": "per-model scaling, cache-read & cache-write ratios (MID)"},
    {"id": "openai-pricing", "kind": "pricing", "year": 2026,
     "title": "OpenAI API pricing",
     "authors": "OpenAI",
     "url": "https://developers.openai.com/api/docs/pricing",
     "finding": "Per-model input/output/cached-input prices for GPT-5.6 and GPT-6 models.",
     "used_for": "per-model scaling (Codex models)"},
    {"id": "mistral", "kind": "industry", "year": 2025,
     "title": "Our contribution to a global environmental standard for AI",
     "authors": "Mistral AI with Carbone 4 and ADEME",
     "url": "https://mistral.ai/news/our-contribution-to-a-global-environmental-standard-for-ai",
     "finding": "45 mL of water per 400-token Le Chat response (full lifecycle, incl. hardware manufacturing).",
     "used_for": "sanity check (different boundary — not mixed in)"},
    {"id": "altman", "kind": "industry", "year": 2025,
     "title": "The Gentle Singularity",
     "authors": "Sam Altman — OpenAI",
     "url": "https://blog.samaltman.com/the-gentle-singularity",
     "finding": "Average ChatGPT query ≈ 0.34 Wh and ≈ 0.000085 gallons (0.32 mL) of water.",
     "used_for": "sanity check"},
    {"id": "epa", "kind": "reference", "year": 2024,
     "title": "WaterSense statistics, toilets and showerheads",
     "authors": "US Environmental Protection Agency",
     "url": "https://www.epa.gov/watersense/statistics-and-facts",
     "alt": ("showerheads", "https://www.epa.gov/watersense/showerheads"),
     "finding": "Toilet flush 1.6 gal (6.06 L) federal max; shower 2.5 gal (9.46 L) per minute.",
     "used_for": "glasses / flushes / shower-minutes comparisons"},
]

# Which sources back each coefficient on the page.
PROVENANCE = {
    "wue": ["aws", "lbnl", "li", "google", "microsoft"],
    "pue": ["aws", "google"],
    "ewif": ["wri", "li", "lbnl"],
    "e_output": ["mlenergy", "oviedo", "google", "couch", "jegham"],
    "e_input": ["couch", "epoch"],
    "cache_read": ["anthropic-pricing", "hausfather", "couch"],
    "cache_write": ["anthropic-pricing", "couch"],
    "model_scale": ["anthropic-pricing", "openai-pricing"],
    "units": ["epa"],
    "checks": ["google", "altman", "li", "mistral", "hausfather"],
}
